### PR TITLE
some visual adjustments in '*Why?:*'

### PR DESCRIPTION
**Pull request by lennonjesus**
Adjusting exhibition of 'Why?' sections.

### CODE REVIEW

**Comment by mgechev** [comment]
Lets keep the "Why?" labels _italic_. When they are bold while reading the guidelines I get distracted by them since the bolder they are the more they seem like titles.

Would you reset the "Bold in 'Why?'" commit and keep only the visual adjustments one?

**Comment by lennonjesus** [comment]
Ok! :)

**Comment by mgechev** [comment]
@lennonjesus last request! Would you squash into a single commit?

**Comment by lennonjesus** [comment]
Done, @mgechev! o/

**Pull request merged**
